spring.application.name=bulletinBoard
server.port=8080

# JPA
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Data base
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bulletinBoard}
spring.datasource.username=${DB_USER:postgres}
# password
spring.datasource.password=${DB_PASSWORD:passwod}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# off automatic migration creation by hibernation
spring.jpa.hibernate.ddl-auto=none

# Flyway settings
spring.flyway.enabled=true
spring.flyway.locations=${DB_MIGRATION_PATH:classpath:db/migration}
spring.flyway.baseline-on-migrate=true

# Flyway logging
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.schema=DEBUG

# Swagger OpenAPI configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.show-actuator=false

# Swagger JWT configuration
springdoc.swagger-ui.oauth.client-id=swagger
springdoc.swagger-ui.oauth.use-pkce=false
springdoc.swagger-ui.oauth.=use-basic-authentication-with-access-code-grant=false

# JWT configuration
jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXNlY3JldC1qd3Qta2V5LWZvci10ZXN0aW5nLXB1cnBvc2VzLTEyMzQ1Ng==}
jwt.expiration=1200000
jwt.refresh-expiration=43200000

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:your-google-client-id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:your-google-client-secret}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

# naming bearer label
springdoc.swagger-ui.authorization-header-name=Authorization

# levels of logging
logging.level.io.jsonwebtoken=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.ru.test.congratulations=DEBUG
logging.level.org.springframework.web=DEBUG

file.upload-dir=uploads/images/